var conf = {
    GROUNDLAYERWIDTH : 700,
    GROUNDLAYERHEIGHT : 400,

    SCORELAYERWIDTH : 700,
    SCORELAYERHEIGHT: 400,

    PLAYERSBALLLAYERWIDTH : 700,
    PLAYERSBALLLAYERHEIGHT: 400,

    NETWIDTH : 6,

    SCOREPOSXPLAYER1 : 300,
    SCOREPOSYPLAYER1 : 55,
    SCOREPOSXPLAYER2 : 365,
    SCOREPOSYPLAYER2 : 55,
    SCOREFONTSIZE : 50,

    BALLWIDTH : 10,
    BALLHEIGHT : 10,
    BALLPOSX : 200,
    BALLPOSY : 200,
///////////////////////////
    PLAYERONEWIDTH : 10,
    PLAYERONEHEIGHT : 70,
    PLAYERONEPOSX : 30,
    PLAYERONEPOSY : 200,

    PLAYERTWOWIDTH : 10,
    PLAYERTWOHEIGHT : 70,
    PLAYERTWOPOSX : 650,
    PLAYERTWOPOSY : 200,

    PLAYERTHREEWIDTH : 10,
    PLAYERTHREEHEIGHT : 70,
    PLAYERTHREEPOSX : 80,
    PLAYERTHREEPOSY : 200,

    PLAYERFOURWIDTH : 10,
    PLAYERFOURHEIGHT : 70,
    PLAYERFOURPOSX : 600,
    PLAYERFOURPOSY : 200,
    /////////////////////
    BLOCCENTERWIDTH : 1010,
    BLOCCENTERHEIGHT : 400,
    BLOCLEFTWIDTH : 150,
    BLOCLEFTHEIGHT : 400,
    BLOCRIGHTWIDTH : 150,
    BLOCRIGHTHEIGHT : 400,
    BLOCDIVGAMEWIDTH : 700,
    BLOCDIVGAMEHEIGHT : 400,

    BUTTONSTARTGAMEWIDTH : 100,
    BUTTONPAUSEGAMEWIDTH : 100,
    BUTTONCONTINUEGAMEWIDTH : 100,
    MOUSECORRECTIONPOSY : 50,

}
